import { useState, useRef } from "react";
import { useNavigate } from "react-router-dom";
import { motion, useScroll, useTransform } from "framer-motion";
import { Button } from "@/components/ui/button";
import { ArrowRight, Sparkles, Check } from "lucide-react";
import DesktopPreview from "@/components/landing/DesktopPreview";



const HeroSection = () => {
  const [email, setEmail] = useState("");
  const navigate = useNavigate();
  
  const containerRef = useRef<HTMLDivElement>(null);
  const { scrollYProgress } = useScroll({
    target: containerRef,
    offset: ["start start", "end end"],
  });

  const scale = useTransform(scrollYProgress, [0, 0.7], [0.85, 1]);
  const rotateX = useTransform(scrollYProgress, [0, 0.7], [25, 0]);
  const translateY = useTransform(scrollYProgress, [0, 0.7], ["60vh", "0vh"]);
  const opacity = useTransform(scrollYProgress, [0, 0.2, 0.7], [0.7, 1, 1]);

  const handleGetStarted = () => {
    navigate("/signup", { state: { email } });
  };

  return (
    <section ref={containerRef} className="relative h-[250vh]">

      {/* The Sticky Stage */}
      <div className="sticky top-0 h-screen overflow-hidden flex flex-col pt-28 lg:pt-36">
        
        {/* Hero Content */}
         <motion.div 
           className="container mx-auto px-4 relative z-10 flex-shrink-0"
           style={{
             opacity: useTransform(scrollYProgress, [0, 0.6], [1, 0]),
             y: useTransform(scrollYProgress, [0, 0.6], [0, -50]),
           }}
        >
          <div className="max-w-4xl mx-auto text-center flex flex-col items-center relative">
            
            {/* Ambient Background Glow */}
            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[300px] h-[300px] md:w-[600px] md:h-[600px] bg-indigo-500/[0.06] dark:bg-indigo-500/[0.12] rounded-full blur-[80px] md:blur-[120px] pointer-events-none -z-10" />

            {/* Left Micro-UI Card */}
            <div className="hidden lg:flex absolute top-24 -left-16 xl:-left-28 animate-float flex-col gap-2 p-3.5 bg-white dark:bg-[#0a0a0a] border border-zinc-200/60 dark:border-white/10 rounded-2xl shadow-[0_8px_30px_rgb(0,0,0,0.04)] dark:shadow-[0_8px_30px_rgb(0,0,0,0.2)] z-20 pointer-events-none">
              <div className="flex items-center gap-3">
                <div className="flex -space-x-2">
                  <div className="w-8 h-8 rounded-full border-2 border-white dark:border-[#0a0a0a] bg-blue-100 dark:bg-blue-900/50 flex items-center justify-center text-[10px] font-medium text-blue-700 dark:text-blue-300">JS</div>
                  <div className="w-8 h-8 rounded-full border-2 border-white dark:border-[#0a0a0a] bg-emerald-100 dark:bg-emerald-900/50 flex items-center justify-center text-[10px] font-medium text-emerald-700 dark:text-emerald-300">AL</div>
                  <div className="w-8 h-8 rounded-full border-2 border-white dark:border-[#0a0a0a] bg-rose-100 dark:bg-rose-900/50 flex items-center justify-center text-[10px] font-medium text-rose-700 dark:text-rose-300">MR</div>
                </div>
                <div className="px-2.5 py-1 bg-green-500/10 text-green-600 dark:text-green-400 text-[10px] font-semibold rounded-full border border-green-500/20">
                  +3 joined
                </div>
              </div>
              <p className="text-[11px] text-muted-foreground text-left font-medium pl-1">Team workspace active</p>
            </div>

            {/* Right Micro-UI Card */}
            <div className="hidden lg:flex absolute top-32 -right-12 xl:-right-24 animate-float [animation-delay:1.5s] flex-col gap-2 p-3 bg-white dark:bg-[#0a0a0a] border border-zinc-200/60 dark:border-white/10 rounded-2xl shadow-[0_8px_30px_rgb(0,0,0,0.04)] dark:shadow-[0_8px_30px_rgb(0,0,0,0.2)] z-20 pointer-events-none">
              <div className="flex items-center gap-3.5">
                <div className="w-8 h-8 rounded-full bg-purple-500/10 flex items-center justify-center shadow-inner">
                  <Sparkles className="w-4 h-4 text-purple-600 dark:text-purple-400" />
                </div>
                <div className="flex flex-col text-left pr-2">
                  <span className="text-xs font-semibold text-foreground">Project Scope</span>
                  <span className="text-[10px] text-muted-foreground">Generated by AI</span>
                </div>
                <div className="w-5 h-5 rounded-full bg-green-500/10 flex items-center justify-center">
                  <Check className="w-3 h-3 text-green-600 dark:text-green-400" />
                </div>
              </div>
            </div>

            {/* Badge (Live Status Indicator) */}
            <div 
              className="inline-flex items-center gap-2.5 px-4 py-1.5 bg-surface-glass-thin backdrop-blur-md rounded-full mb-8 animate-fade-in border border-white/5"
              style={{ boxShadow: 'var(--shadow-sm)' }}
            >
              {/* Pulsing Dot */}
              <span className="relative flex h-2 w-2">
                <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-task-green opacity-75"></span>
                <span className="relative inline-flex rounded-full h-2 w-2 bg-task-green"></span>
              </span>
              <span className="text-xs font-medium tracking-wide text-foreground/80">
                Public Beta 1.0
              </span>
            </div>

            {/* Heading with Cursor Wrappers */}
            <div className="relative inline-block">


              <h1 className="text-4xl sm:text-5xl md:text-6xl lg:text-7xl xl:text-8xl font-bold tracking-tighter mb-6 text-foreground leading-[1.05]">
                Build software,
                <br />
                <span className="text-foreground/80">together.</span>
              </h1>
            </div>

            {/* Subheading */}
            <p className="text-lg md:text-xl text-muted-foreground max-w-2xl mx-auto mb-10 leading-relaxed font-normal">
              Planning, tasks, and communication in one focused workspace.
            </p>

            {/* Liquid Glass CTAs */}
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4 mb-20 animate-fade-in-up">
              <Button 
                size="lg" 
                className="h-12 px-8 rounded-full text-base font-medium group active:scale-95 transition-transform"
                style={{ boxShadow: 'var(--shadow-elevation2)' }}
                onClick={handleGetStarted}
              >
                Get Started
                <ArrowRight className="w-4 h-4 ml-2 group-hover:translate-x-1 transition-transform" />
              </Button>
              <Button 
                variant="outline"
                size="lg"
                onClick={() => document.getElementById('features')?.scrollIntoView({ behavior: 'smooth' })}
                className="h-12 px-8 rounded-full text-base font-medium bg-surface-glass-regular backdrop-blur-md border-white/5 hover:bg-white/5 group active:scale-95 transition-all"
              >
                Explore How It Works
                <ArrowRight className="w-4 h-4 ml-2 group-hover:translate-x-1 transition-transform" />
              </Button>
            </div>
          </div>
        </motion.div>

        {/* 3D Context & Dashboard Preview */}
        <div className="absolute top-0 left-0 w-full h-full flex flex-col items-center justify-end pb-4 lg:pb-6 pointer-events-none [perspective:2000px] z-20">
          <motion.div 
            className="w-full px-4 sm:px-6 lg:px-8 origin-[50%_0%] pointer-events-auto"
            style={{
              scale,
              rotateX,
              y: translateY,
              transformStyle: "preserve-3d"
            }}
          >
            {/* MacBook Pro Frame Wrapping the Preview */}
            <div 
              className="relative mx-auto rounded-[1rem] sm:rounded-[2rem] lg:rounded-[2.5rem] bg-[#2a2b2c] p-[3px] sm:p-[5px] lg:p-[6px] flex flex-col shadow-elevation5 ring-1 ring-black/20 dark:ring-white/10"
              style={{ 
                backgroundImage: 'linear-gradient(to bottom, #3a3b3c, #1c1d1e)',
                aspectRatio: '16/10',
                width: '100%',
                maxWidth: 'min(1400px, 140vh)'
              }}
            >
              {/* Inner Black Bezel */}
              <div className="relative rounded-[0.8rem] sm:rounded-[1.8rem] lg:rounded-[2.2rem] bg-black p-1.5 sm:p-3 md:p-4 flex flex-col w-full flex-1 overflow-hidden border border-white/10">
                
                {/* Camera Notch */}
                <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[80px] sm:w-[120px] md:w-[160px] h-[16px] sm:h-[24px] md:h-[28px] bg-black rounded-b-[0.5rem] sm:rounded-b-[1rem] z-50 flex items-center justify-center">
                  <div className="w-1.5 h-1.5 sm:w-2 sm:h-2 md:w-2.5 md:h-2.5 rounded-full bg-[#111] shadow-inner border border-white/5 flex items-center justify-center">
                    <div className="w-0.5 h-0.5 md:w-1 md:h-1 rounded-full bg-blue-500/50" />
                  </div>
                </div>

                {/* The Screen / Preview */}
                <div 
                  className="relative rounded-[0.5rem] sm:rounded-[1rem] lg:rounded-[1.2rem] bg-background border border-border/50 w-full flex-1 overflow-hidden"
                  style={{
                    boxShadow: 'inset 0 0 0 1px rgba(255,255,255,0.05)'
                  }}
                >
                  <DesktopPreview />
                </div>
              </div>
            </div>
          </motion.div>
        </div>
      </div>
    </section>
  );
};

export default HeroSection;